use_frameworks!

platform :ios, '14.0'

target 'xAlgoPod_Example' do
  pod 'xAlgoPod', :path => '../'

  target 'xAlgoPod_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
